<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>if1</string>
	</array>
	<key>name</key>
	<string>IF1</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\d+</string>
			<key>name</key>
			<string>constant.numeric.if1</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^C(.)*$</string>
			<key>name</key>
			<string>comment.line.if1</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\%(.)*$</string>
			<key>name</key>
			<string>comment.line.if1</string>
		</dict>
		<dict>
			<key>match</key>
			<string>E</string>
			<key>name</key>
			<string>variable.parameter.if1</string>
		</dict>
		<dict>
			<key>match</key>
			<string>L</string>
			<key>name</key>
			<string>variable.language.if1</string>
		</dict>
		<dict>
			<key>match</key>
			<string>N</string>
			<key>name</key>
			<string>support.function.if1</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[GXI]</string>
			<key>name</key>
			<string>entity.name.function.if1</string>
		</dict>
		<dict>
			<key>match</key>
			<string>T</string>
			<key>name</key>
			<string>entity.name.type.if1</string>
		</dict>
		<dict>
			<key>match</key>
			<string>"(.)*"</string>
			<key>name</key>
			<string>string.quoted.double.if1</string>
		</dict>
		<dict>
			<key>match</key>
			<string>Compound</string>
			<key>name</key>
			<string>keyword.operator.if1</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\{</string>
			<key>end</key>
			<string>^\}</string>
			<key>name</key>
			<string>meta.block.if1</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.if1</string>
	<key>uuid</key>
	<string>a0d296eb-5cfc-4c46-8aec-de1d633320c1</string>
</dict>
</plist>
