.\" DVM Man Page
.\" Copyright (c) 2013, 2014 Mathijs Saey
.\" All Rights Reserved
.TH DVM 1 "6 March 2014" VUB dvm

.SH NAME
DVM \-\- The Dataflow Virtual Machine

.SH SYNOPSIS
dvm [-c cores][-i input][-ll logLevel][--dot][--dry_run] path

.SH DESCRIPTION
Runs the DIS file specified by path on the dataflow based virtual machine. The VM will accept input until it's main function has received all of it's data. And terminate once the main function received enough results.

If - is provided as path, dvm will read the DIS file from stdin. In this case, all the inputs of the main function should be provided through the command line.

.SH OPTIONS

.HP 
-c cores, --cores cores
.br
Determine the amount of cores that DVM will use to execute the program. This is set to the amount of logical cores in your system by default.

.HP
-i input, --input input
.br
Pass input to the Virtual machine. By default, DVM will keep on asking for input until it has received as many inputs as the main function needs. This argument can be added to send an argument to main before DVM asks for it. This option can be repeated to send multiple inputs to DVM.

.HP
-ll logLevel, --logLevel
.br
Determine the loglevel of DVM, useful to find bugs. Logging is disabled by default.

.HP
--dot
.br
Generate a dot graph of the input file. This requires graphviz dot to be in your path.
This will store the generated dot file in dis.dot and it's generated graph in dis.dot.png

.HP
--dry_run
.br
Abort DVM just before starting the runtime. This can be useful if you only want to generate a dot
graph without actually running anything.