<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sis</string>
	</array>
	<key>name</key>
	<string>Sisal</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\d+</string>
			<key>name</key>
			<string>constant.numeric.sis</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\%.*$</string>
			<key>name</key>
			<string>comment.line.sis</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[|&lt;&gt;=:+-]</string>
			<key>name</key>
			<string>keyword.operator.sis</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\sif\s|\sthen\s|\selse\s|\slet\s|\send\s|\swhen\s|\sof\s|\sfor\s|\sin\s|\sreturns\s|\sdefine\s)</string>
			<key>name</key>
			<string>keyword.control.sis</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(function)\s(\S*)\s*\(((?:.)*)\s(returns)\s((?:.)*)\)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.sis</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.sis</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.sis</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.control.sis</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.sis</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(end)\sfunction</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.sis</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.sis</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.sis</string>
	<key>uuid</key>
	<string>73d84f0a-ef0c-43ca-a2f9-994afbf0e845</string>
</dict>
</plist>
