.Dd 27/01/2014              \" DATE 
.Dt DVM 1                  \" Program name and manual section number 
.Os Darwin
.Sh NAME                
.Nm DVM
.Nd DataFlow Virtual Machine
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Sh DESCRIPTION          \" Section Header - required - don't modify
